### ISSUE TITLE
Enhance UI16 Filter for Full Text search breaks expected filter results

### ISSUE THREAD

**Issue by karbonfybar** [arnoudkooi/ServiceNow-Utils#119]
Current version: SN Utils 5.2.0.1
Browser: Chrome 92.0.4515.107
Setting: Enhance UI16 Filter for Full Text search

![SNUtils_settings](https://user-images.githubusercontent.com/18409255/127181332-a0118b43-2e81-4548-8090-26e61448358c.png)

Appears to break the expected left nav filter. See attached screenshot. Type the letters "rd re" in the left nav filter with the expectation of seeing Password Reset Application.

Filter results now appear to return any combination of "rd" and/or "re". 

![left_nav_filter_results](https://user-images.githubusercontent.com/18409255/127179947-8093e8cd-3a0f-4c7e-a721-c65e727c8211.png)

Unchecking the box next to the setting and reloading browser window immediately corrects the issue.

![left_nav_filter_results_fixed](https://user-images.githubusercontent.com/18409255/127180961-70b2cdd4-dc6b-48b2-a0c8-6067e09ae8cd.png)

Was this an expected result of this setting? I do not see any documentation about how this setting is to work. Unchecking the setting fixed my issue and so far I don't see any adverse side affects of having that off.

**Comment by arnoudkooi** [comment]
It is by design, but there seems to be a bug, it matches on each of the words in the hierarchy, see this [tweet](https://twitter.com/sn_utils/status/1419575838815686656) and below screenshot. (check my tweets for all updates).

I will have a look at this, for now disabling is the way to go..

![image](https://user-images.githubusercontent.com/840781/127229384-48c5a651-0c7e-446d-947e-9fe06a37686d.png)

**Comment by arnoudkooi** [comment]
Removed the feauture
