### ISSUE TITLE
Feature Request: Firefox support for ScriptSyncer?

### ISSUE THREAD

**Issue by heroje** [arnoudkooi/ServiceNow-Utils#17]
Hi,
I've installed the [Firefox version of your extension ](https://addons.mozilla.org/nl/firefox/addon/servicenow-utils2/) after having to switch from Ungoogled Chromium due to its old version breaking some pages.
Is ScriptSyncer missing in the version for this browser? The addon's description says that it could be hidden somewhere/somehow?
> - Edit scripts on filesytem, in own texteditor or IDE and automaticly save to instance!!

**Comment by arnoudkooi** [comment]
I have hidden the SciptSyncer tab via CSS in Firefox, I don't believe it works in FireFox does it @wiiaboo?

**Comment by arnoudkooi** [comment]
I can post the code in a new repo.

Im thinking of replacing this with a Visual Code extension as Chrome Apps are deprecated and being faced out.

**Comment by wiiaboo** [comment]
It would need a native app to be coded and connected to it. The APIs Chrome uses for Apps aren't part of the Web-Extensions standard.

**Comment by arnoudkooi** [comment]
No ff support availablefor chrome apps, Im working on a VS code extension as an alternativ. Will close this now

**Comment by arnoudkooi** [comment]
Please check out the new VS Code extension :)
https://marketplace.visualstudio.com/items?itemName=arnoudkooicom.sn-scriptsync

**Comment by wiiaboo** [comment]
Looks nice, by the video.

Some questions though:
- Do you need the tabs for each record to remain open for the syncing to work?
- How does it handle multiple people editing the same remote record at the same time?
- How does it work, locally? Is a local copy saved in the current workspace?
- Can/will we be able to do something like "link this remote script/text field in this specific record to a specific local file in VSCode?"

**Comment by arnoudkooi** [comment]
Just try ;)

Do you need the tabs for each record to remain open for the syncing to work?
No

How does it handle multiple people editing the same remote record at the same time?
No handling for that scenario. (just like the normal editor?)

How does it work, locally? Is a local copy saved in the current workspace?
Yes, it's saved in the structure Instance>Table>RecordField
Im considering to autodelete these after a few hours, so that SN stays the source of truth

Can/will we be able to do something like "link this remote script/text field in this specific record to a specific local file in VSCode?"
I would like to keep it as stuctured, low config as possible, what would be the usecase?
