### ISSUE TITLE
Copycells does not copy full cell text when overflowed by ...

### ISSUE THREAD

**Issue by swobodis** [arnoudkooi/ServiceNow-Utils#318]
https://github.com/arnoudkooi/ServiceNow-Utils/blob/528f4212d0971ff05cca08971217214753a6c023/inject.js#L3229-L3247
If a cell has too much data in it and the display is cut off and appended by ... 
The "copycells" slashcommand copies the ... at the end and not the actual cell contents. 

Looking at the HTML it seems it is possible to go to the parent TD and use the "data-original-title" attribute to get the full cell contents.

**Comment by arnoudkooi** [comment]
I have looked at this, the property you mention data-original-title is capped at 1000 characters

Besides the way excel copies text is placing each cell text value between double quotes and escapes existing double quotes with a double quote.
Otherwise, each new line would be pasted to a new cell in Excel.
I tried to replicate it.

When the data-original-title has a length of 1000 I keep using the cell value, with the postfix [TRUNCATED]

<img width="791" alt="image" src="https://user-images.githubusercontent.com/840781/200412475-5e636519-418f-4940-92eb-f3e71521d6ca.png">

Will do some tests and include this in the next update.

**Comment by swobodis** [comment]
Thank you very much for looking into this. I had no idea it was capped to 1000 char, but that makes sense. I think adding the truncated if it goes over that is a good idea as it is clearer. This will at least help though for some shorter field lengths that get cut off.

**Comment by arnoudkooi** [comment]
Fix is now published in 6.3.0.0, please let me know if it works

**Comment by arnoudkooi** [comment]
Hope it works better now

**Comment by swobodis** [comment]
Thank you very much! This has been working so much better for me.

On Nov 18, 2022, at 3:04 PM, arnoudkooi ***@***.***> wrote:

﻿

Hope it works better now
