### ISSUE TITLE
Vivaldi 6.0 Update broke the extension

### ISSUE THREAD

**Issue by lordyj2001** [arnoudkooi/ServiceNow-Utils#390]
When I updated to Vivaldi version 6 it broke the extension.
Normally when the extension gets updated or the browser I have to remove it and add it back to get it working again.

This time when I tried to remove it the browser would only crash to desktop.
Steps:
Have extension installed.
From Chrome web store click Remove Extension
Browser crashes to desktop
----------------------------
From the right clicking the extension
Click Remove Extension
Browser crashes to desktop

----------------------------
It also crashes when trying to disable it
From Extension Manager
Click the toggle to disable.
Browser crashes to desktop

I have attached the DMP file from the browser. I don't know if this will help at all.

[ac2a0621-8769-4916-8eb7-52a13e353209.zip](https://github.com/arnoudkooi/ServiceNow-Utils/files/11346321/ac2a0621-8769-4916-8eb7-52a13e353209.zip)

**Comment by arnoudkooi** [comment]
Thanks, after your remark on the Chrome Webstore I submitted below bug report.
I have no update so far, and no idea how to troubleshoot...

Thank you for submitting a bug report to Vivaldi. We depend on reports from the Vivaldi community to find and fix bugs.

These are the details that you provided:

-------------------------------------------------------------------------------
             Summary: Vivaldi crashes when Extension SN Utils is diabled or unisntalled
                 Key: VB-96840
             Project: Vivaldi Browser

         Environment: Vivaldi version: 6.0.2979.15 (Stable channel) (arm64)
Operating System: macOS 13.3.0 (arm 64bit)
Device model:
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[112.0.0.0](http://112.0.0.0/) Safari/537.36

         Attachments: 9707894e-6180-49c8-aced-6438d23864bb.dmp
Vivaldi crashes when Extension SN Utils is diabled or unisntalled

*Steps to reproduce:*
- Install SN Utils from https://chrome.google.com/webstore/detail/sn-utils-tools-for-servic/jgaodbdddndbaijmcljdbglhpdhnjobg?hl=en-GB&authuser=0
- Try to disable the extension
- Vivaldi crashes

*Expected behaviour:*
Extension disabled (or removed)

*Actual behaviour:*
Vivaldi immediately crashed

**Comment by arnoudkooi** [comment]
Are you on Windows or Mac?
Could you please chime in on this discussion?
https://forum.vivaldi.net/topic/86821/removing-extension-crashes-vivaldi/13

**Comment by lordyj2001** [comment]
I have answered. I am on Win 10 Pro for both locations I am experiencing the issue.

**Comment by arnoudkooi** [comment]
Did you try the snapshot release? That fixed it for me.

**Comment by arnoudkooi** [comment]
This is a Vivaldi issue, closing this issue. If it is not updated in the following release of the  stable channel, please comment and Ill look at it again.
