### ISSUE TITLE
Slashcommand /copycells from issue #318, when overflow and instead pulled form HTML attribute quote is added to data

### ISSUE THREAD

**Issue by swobodis** [arnoudkooi/ServiceNow-Utils#458]
When the cell you are copying is overflowing on the list view. We are able to copy the cell still since utils is grabbing the HTML attribute information. However, there is a difference between grabbing from the attribute and the html text. 

Example, list that does not end in "..." copy's without " wrapping text
List that ends in "..." wraps text in "example text"

```
"Mobile - Transfer Order - Generate Packing slip"
Transfer order line item - Cancel button
Transfer order - Cancel button
```

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/11360305/39176ea5-dc65-49fd-b2cc-6650b266add3)

**Comment by CritchCode** [comment]
I like the way it works right now but I do have a related follow-on question. There are 4 scenarios that I can see...

My question is why does scenario 3 end up with encapsulation?

|  | Selected cell contains... | Output | Example on the clipboard | Notes |
| --- | --- | --- | --- | --- |
| 1 | Value that doesn't get truncated and doesn't contain line breaks | No encapsulation | This is text |  |
| 2 | Value that doesn't get truncated and contains line breaks | Encapsulated value | "Text line 1<br/>Text line 2" | Relies on user prefs allowing line breaks in lists |
| 3 | Value that gets truncated and doesn't contain line breaks | Encapsulated value | "This is a long text without line breaks that gets truncated" |  |
| 4 | Value that gets truncated and contains line breaks | Encapsulated value | "This is a long text with<br/>line breaks that gets truncated<br/>because it has<br/>many<br/>many<br/>many<br/>many<br/>lines" |  |

**Comment by arnoudkooi** [comment]
> why does scenario 3 end up with encapsulation

Because It works as developed ;) 
I'll change that one to remove the double quotes.

**Comment by swobodis** [comment]
> That is intentional, if your text contains line breaks, it will work as expected (keep the data in 1 cell) when pasting the result into Excel. What is the problem you're experiencing with this?

Okay, I was expecting it to not wrap in quotes if there were no line breaks. In my screenshot I was copying short_description which is not multiline, but it was still getting encapsulated. So, it was confusing to me when I copied out to a word doc and some lines were encapsulated and others were not.

**Comment by arnoudkooi** [comment]
Good point, I just added a check for line breaks. I accidentally referred to issue #318 instead of this one in the commit message and release notes)

**Comment by arnoudkooi** [comment]
Could you check if it works now?

**Comment by swobodis** [comment]
Works! Thank you very much
________________________________
