### ISSUE TITLE
"[SN Utils] Versions" - no context menu 

### ISSUE THREAD

**Issue by saintnicster** [arnoudkooi/ServiceNow-Utils#504]
Steps to reproduce
1. Navigate
https://&lt;instance&gt;.service-now.com/now/nav/ui/classic/params/target/sys_ui_style.do%3Fsys_id%3D2ed4f42bef002000a7450fa3f8225615%26sysparm_view%3DGlobal
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/392215/5bed2266-25b7-4119-830d-0d7a33988e23)

2. Click on the [SN Utils] Versions ()" text at the bottom of Related Links
3. Right click on a line 

Expected results
4. See the glide-style context menu 
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/392215/be098970-b597-4cfc-9643-3a640051cdf6)

Actual Results
5. Chrome right click menu is seen
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/392215/201d8653-e8f7-4fe7-b47a-537dc8b00c49)
6. Looking in Web console, seeing "Is not defined" messages
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/392215/84183a7c-c59c-4eca-908b-07e08ea0fb02)

Work-around:  If I add a related list, the right clicking works

**Comment by arnoudkooi** [comment]
Another workaround is changing the "Load related list" setting to something other then "With the form"
I think I'll add a check that opens a new tab instead of modal or shows a message when GlideList2 is not loaded
![Google Chrome20240520 - 2230](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/25cef4b3-4abd-4c8e-a9c6-2e9f5d52ce4c)

**Comment by arnoudkooi** [comment]
Fix is now implemented, ok now?

**Comment by saintnicster** [comment]
Confirmed.  Thanks!
