### ISSUE TITLE
Improvement: /unimp command

### ISSUE THREAD

**Issue by mrlexley** [arnoudkooi/ServiceNow-Utils#79]
Currently, the "/unimp" command only un impersonates users that have a snc_internal role.
So you can't log out when you have impersonated a CSM customer, because of the security on: "sys_unimpersonate.do".
Now you need to use the /imp command and click on your recent impersonation. 

Would it be possible to add a command where you end the impersonation directly also when you impersonated a CSM customer?
Preferably with a redirect to the backend.

**Comment by wiiaboo** [comment]
It would have to run server-side code to do a `gs.getSession().onlineUnimpersonate();` and you can't use sys.script.do on a non-admin user, so I don't think it's possible to do it through SN-Utils.

**Comment by arnoudkooi** [comment]
Calling the `/api/now/ui/impersonate/` API with the original sys_id would be an option, but that would be rather complex, to store the original sys_id. If someone has a good idea, let me know, otherwise i'll close this one.

**Comment by arnoudkooi** [comment]
As stated dont see an easy way, so please use the /imp for now...

**Comment by arnoudkooi** [comment]
I have updated the `/imp` and `/unimp` command. Please check if it works for you now!
https://twitter.com/sn_utils/status/1396589836518232069

Please check if this works in your scenario!

**Comment by wiiaboo** [comment]
Hey @arnoudkooi ,

The `/imp` command seems to work fine, but not the `/unimp` one, at least on impersonating a non-admin user.

**Comment by arnoudkooi** [comment]
I tested on FireFox and seemed to work, do you have more details?

**Comment by wiiaboo** [comment]
Hm, right. Might be another in a long list of issues from working on a very old instance that's been upgraded since Instabul or earlier.

I can't reproduce the issue on another more recent instance.

**Comment by wiiaboo** [comment]
I really don't know unless I start debugging the addon code itself.

It seems that, with the old instance, that request being done in snuImpersonater https://github.com/arnoudkooi/ServiceNow-Utils/blob/319e3ca32c8d92a5a01d7f9ee0a8f8cb14dd4179/inject.js#L3125
there's no "user.impersonation" string present in the response text.
There's no reference of my user_name anywhere in the HTML in fact, so this solution cannot be used with this old instance at all.

The new instance (Orlando, not that new), versus the very old instance that's been upgraded since forever, even though it's Quebec have different ways in the HTML of displaying the original user.
New instance has the user_name, old instance has the Sys ID of the original user, found with this regex: `([0-9a-f]{32})(?='\)" id="glide_ui_unimpersonate")`

**Comment by arnoudkooi** [comment]
If there are still isuues, let me know. It works on my personal instance, original Helsinki
