### ISSUE TITLE
Search all configured tables for sn_codesearch.Default Search Group

### ISSUE THREAD

**Issue by jacebenson** [arnoudkooi/ServiceNow-Utils#86]
https://github.com/arnoudkooi/ServiceNow-Utils/blob/master/codesearch.js#L134

So here it's hard coded, however if we don't set the tables there and instead to a lookup to /sn_codesearch_table_list.do?sysparm_query=search_group%3D9a44f352d7120200b6bddb0c82520376 we will get back a list of each table.  then as sn adds more tables (today its at 31) they are included.  If folks want to search more things they can just add the code search table to the instance.

**Comment by jacebenson** [comment]
Or allow the list to be configurable w/a default.

**Comment by arnoudkooi** [comment]
Thanks Jace, hope to do some more work on it, for now: https://youtu.be/cOMS_h7tHOM

**Comment by arnoudkooi** [comment]
As suggested it now follows the configured tables in the Default Search Group.

- It falls back to the 31 default tables, these are hardcoded in an array and put in an order so that most common are on top
- If a configured table is added to the Code Search Tables, it will be searched first
- At the top of the page anchor links now appear to jump to a specific result
- At the bottom there is a link to the tabe list in the instance.

![image](https://user-images.githubusercontent.com/840781/100925992-091c4400-34e3-11eb-9e34-e184a33db13c.png)

Hope this works as desired!
